import sys
import os
import time

sys.path.append(
    os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..")
    )
)

import streamlit as st
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt

from digital_twin.network_topology import create_network

# =========================================================
# PAGE CONFIG
# =========================================================
st.set_page_config(
    page_title="Cybersecurity Digital Twin",
    layout="wide"
)

# =========================================================
# TITLE
# =========================================================
st.title("AI-Based Cybersecurity Digital Twin")

st.markdown(
    """
    Real-Time Threat Detection and Automatic Node Isolation
    """
)

# =========================================================
# FILE PATHS
# =========================================================
STATUS_PATH = "logs/live_node_status.csv"

ATTACK_LOG_PATH = "logs/live_attack_log.csv"

# =========================================================
# AUTO REFRESH
# =========================================================
refresh = st.sidebar.slider(
    "Refresh Rate (seconds)",
    1,
    10,
    3
)

# =========================================================
# LOAD NODE STATUS
# =========================================================
if not os.path.exists(STATUS_PATH):

    st.error(
        f"Status file not found:\n{STATUS_PATH}"
    )

    st.stop()

alerts = pd.read_csv(STATUS_PATH)

alerts.columns = [
    col.strip().lower().replace(" ", "_")
    for col in alerts.columns
]

# =========================================================
# BUILD NODE STATUS DATA
# =========================================================

# Live detector currently stores risk + anomaly_score
# in Node_A -> Node_E order.

node_names = [
    "Node_A",
    "Node_B",
    "Node_C",
    "Node_D",
    "Node_E"
]

alerts = alerts.copy()

# Assign node names according to detector order
alerts["node"] = node_names[:len(alerts)]

# Read isolated nodes generated by live detection
ISOLATED_PATH = "logs/isolated_nodes.csv"

isolated_nodes = set()

if os.path.exists(ISOLATED_PATH):
    isolated_df = pd.read_csv(ISOLATED_PATH)

    if "node" in isolated_df.columns:
        isolated_nodes = set(
            isolated_df["node"].astype(str).str.strip()
        )

# Determine node state
alerts["state"] = alerts["node"].apply(
    lambda x: "ISOLATED"
    if x in isolated_nodes
    else "ACTIVE"
)

# Clean risk
alerts["risk"] = (
    alerts["risk"]
    .astype(str)
    .str.upper()
)

# Clean anomaly score
alerts["anomaly_score"] = pd.to_numeric(
    alerts["anomaly_score"],
    errors="coerce"
).fillna(0.0)

# Attack count
alerts["attacks_detected"] = 0

# Final column order
alerts = alerts[
    [
        "node",
        "state",
        "risk",
        "anomaly_score",
        "attacks_detected"
    ]
].copy()
# =========================================================
# CLEAN DATA
# =========================================================
alerts["node"] = alerts["node"].astype(str)

alerts["state"] = (
    alerts["state"]
    .astype(str)
    .str.upper()
)

alerts["risk"] = (
    alerts["risk"]
    .astype(str)
    .str.upper()
)

alerts["anomaly_score"] = pd.to_numeric(
    alerts["anomaly_score"],
    errors="coerce"
).fillna(0.0)

alerts["attacks_detected"] = pd.to_numeric(
    alerts["attacks_detected"],
    errors="coerce"
).fillna(0).astype(int)

# =========================================================
# NETWORK METRICS
# =========================================================
total_nodes = len(alerts)

isolated_nodes = len(
    alerts[
        alerts["state"] == "ISOLATED"
    ]
)

high_risk = len(
    alerts[
        alerts["risk"] == "HIGH"
    ]
)

medium_risk = len(
    alerts[
        alerts["risk"] == "MEDIUM"
    ]
)

# =========================================================
# METRIC CARDS
# =========================================================
st.subheader("Network Metrics")

col1, col2, col3, col4 = st.columns(4)

col1.metric(
    "Total Nodes",
    total_nodes
)

col2.metric(
    "Isolated Nodes",
    isolated_nodes
)

col3.metric(
    "High Risk Nodes",
    high_risk
)

col4.metric(
    "Medium Risk Nodes",
    medium_risk
)

# =========================================================
# DIGITAL TWIN NETWORK GRAPH
# =========================================================
st.subheader("Live Network Topology")

G = create_network()

fig, ax = plt.subplots(figsize=(12, 8))

pos = nx.spring_layout(
    G,
    seed=42
)

color_map = []

# ---------------------------------------------------------
# NODE COLORS
# ---------------------------------------------------------
for node in G.nodes():

    if node in alerts["node"].values:

        row = alerts.loc[
            alerts["node"] == node
        ].iloc[0]

        state = row["state"]

        risk = row["risk"]

        if state == "ISOLATED":

            color_map.append("red")

        elif risk == "HIGH":

            color_map.append("red")

        elif risk == "MEDIUM":

            color_map.append("orange")

        else:

            color_map.append("green")

    else:

        color_map.append("lightgray")

# ---------------------------------------------------------
# DRAW NETWORK
# ---------------------------------------------------------
nx.draw(
    G,
    pos,
    with_labels=True,
    node_size=2800,
    node_color=color_map,
    font_size=10,
    font_weight="bold",
    edge_color="gray",
    ax=ax
)

ax.set_title(
    "Cybersecurity Digital Twin Network",
    fontsize=14,
    fontweight="bold"
)

st.pyplot(fig)

# =========================================================
# NODE STATUS TABLE
# =========================================================
st.subheader("Live Node Status")

display_df = alerts.rename(columns={

    "node": "Node",

    "state": "State",

    "risk": "Risk",

    "anomaly_score": "Anomaly Score",

    "attacks_detected": "Attacks Detected"
})

st.dataframe(
    display_df,
    use_container_width=True
)

# =========================================================
# ATTACK DISTRIBUTION
# =========================================================
st.subheader("Attack Distribution")

chart_data = alerts[[
    "node",
    "attacks_detected"
]].copy()

chart_data.columns = [
    "Node",
    "Attacks"
]

st.bar_chart(
    chart_data.set_index("Node")
)

# =========================================================
# ANOMALY SCORE VISUALIZATION
# =========================================================
st.subheader("Anomaly Scores")

score_data = alerts[[
    "node",
    "anomaly_score"
]].copy()

score_data.columns = [
    "Node",
    "Score"
]

st.line_chart(
    score_data.set_index("Node")
)

# =========================================================
# LIVE ATTACK LOGS
# =========================================================
st.subheader("Recent Attack Logs")

if os.path.exists(ATTACK_LOG_PATH):

    attack_logs = pd.read_csv(
        ATTACK_LOG_PATH
    )

    st.dataframe(
        attack_logs.tail(20),
        use_container_width=True
    )

else:

    st.info(
        "No attack logs available yet."
    )

# =========================================================
# AUTO REFRESH
# =========================================================
time.sleep(refresh)

st.rerun()